# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
copyright: © Russell Keith-Magee

nav:
  - About:
      - about/index.md
      - What is BeeWare?: about/overview.md
      - The Bee Team: about/team.md
      - History and Philosophy: about/history.md
      - Contact: about/contact.md
      - Branding guidelines: about/branding.md
  - Documentation:
      - docs/index.md
  - Community:
      - community/index.md
      - BeeWare Community Code of Conduct: community/code-of-conduct.md
      - Governance: community/governance.md
  - Contributing:
      - contributing/index.md
      - First-time contributors: contributing/first-time-contributors.md
      - Contribution guide:
          - contributing/guide/index.md
          - Fix an issue: contributing/guide/what/fix-issue.md
          - Implement a new feature: contributing/guide/what/implement-feature.md
          - Write documentation: contributing/guide/what/write-docs.md
          - Triage an issue: contributing/guide/what/triage.md
          - Review a pull request: contributing/guide/what/review-pr.md
          - Propose a new feature: contributing/guide/what/propose-feature.md
          - Translate content: contributing/guide/what/translate.md
          - Use the tools: contributing/guide/what/use-tools.md
          - Setting up a development environment: contributing/guide/how/dev-environment.md
          - Reproducing an issue: contributing/guide/how/reproduce-issue.md
          - Working from a branch: contributing/guide/how/branches.md
          - Avoiding scope creep: contributing/guide/how/scope-creep.md
          - Writing, running, and testing code: contributing/guide/how/write-code.md
          - Building documentation: contributing/guide/how/build-docs.md
          - Writing documentation: contributing/guide/how/write-docs.md
          - Adding a change note: contributing/guide/how/change-note.md
          - Submitting a pull request: contributing/guide/how/submit-pr.md
          - Providing a review: contributing/guide/how/review-pr.md
          - Submitting a new issue: contributing/guide/how/new-issue.md
          - Proposing a new feature: contributing/guide/how/propose-feature.md
          - Translating content: contributing/guide/how/translate.md
          - Pull request review process: contributing/guide/next/pr-review.md
          - Release process: contributing/guide/next/release.md
          - AI Policy: contributing/guide/policies/ai-policy.md
          - Code style guide: contributing/guide/style/code-style-guide.md
          - Documentation style guide: contributing/guide/style/docs-style-guide.md
      - Sprint guide: contributing/sprint-guide.md
      - Challenge coins: contributing/challenge-coins.md
  - News:
      - news/index.md
  - Sponsor:
      - membership/index.md

not_in_nav: |
  /index.md
  /titles.md
  /project/README.md

exclude_docs: |  # This is the only way to keep the build from parsing the team bio files.
  !.*
  /about/team/

validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  anchors: warn
  unrecognized_links: warn

extra:
  project_name: beeware
  formal_name: BeeWare
  hide_dev_links: true
  website: true
  translated: true
  min_python_version: "3.10"  # The oldest supported Python version
  min_python_version_tag: "310"  # The tag version of the minimum python version
  recent_python_version: "3.13"  # The newest Python version known to work on all platforms
  docs_python_version: "3.13"  # The version of Python required to build the documentation
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beeware
      name: BeeWare on GitHub
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@beeware
      name: BeeWare on Mastodon
    - icon: fontawesome/brands/discord
      link: https://beeware.org/bee/chat/
      name: BeeWare on Discord
    - icon: fontawesome/solid/square-rss
      name: BeeWare blog RSS feed
      link: https://beeware.org/news/buzz/atom.xml
  github_icon: <i class="fa-github fa-brands" aria-hidden="true"></i>
  generator: false
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: العَرَبِيَّة
      link: /ar/
      lang: ar
    - name: Čeština
      link: /cs/
      lang: cs
    - name: Dansk
      link: /da/
      lang: da
    - name: Deutsch
      link: /de/
      lang: de
    - name: Español
      link: /es/
      lang: es
    - name: فارسی
      link: /fa/
      lang: fa
    - name: Français
      link: /fr/
      lang: fr
    - name: Italiano
      link: /it/
      lang: it
    - name: 日本語
      link: /ja/
      lang: ja
    - name: 한국어
      link: /ko/
      lang: ko
    - name: Polski
      link: /pl/
      lang: pl
    - name: Português
      link: /pt/
      lang: pt
    - name: Русский
      link: /ru/
      lang: ru
    - name: Türkçe
      link: /tr/
      lang: tr
    - name: Tiếng Việt
      link: /vi/
      lang: vi
    - name: 中文(简体)
      link: /zh_CN/
      lang: zh-Hant
    - name: 中文(繁體)
      link: /zh_TW/
      lang: zh-TW


extra_css:
  - stylesheets/beeware.css

theme:
  name: material
  language: en
  logo: assets/images/brutus-256.png
  favicon: assets/images/brutus-256.png
  features:
    - content.tabs.link
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  # PyMdown Extensions
  pymdownx.highlight: {}
  pymdownx.superfences: {}
  pymdownx.blocks.caption: {}
  pymdownx.blocks.admonition:
    types:
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  pymdownx.blocks.details:
    types:
      - {name: details-note, class: note}
      - {name: details-abstract, class: abstract}
      - {name: details-info, class: info}
      - {name: details-tip, class: tip}
      - {name: details-success, class: success}
      - {name: details-question, class: question}
      - {name: details-warning, class: warning}
      - {name: details-failure, class: failure}
      - {name: details-danger, class: danger}
      - {name: details-bug, class: bug}
      - {name: details-example, class: example}
      - {name: details-quote, class: quote}
  pymdownx.blocks.tab:
    alternate_style: true
  pymdownx.snippets:
    base_path: ["docs"]
    url_download: true
    check_paths: true
  # Python Markdown extensions
  toc:
    permalink: true
    title: On this page
  attr_list: {}
  md_in_html: {}
  smarty:
    smart_quotes: false

plugins:
  search: {}
  blog:
    blog_dir: news
    post_url_date_format: yyyy
    post_url_format: "{categories}/{date}/{slug}"
    post_url_max_categories: 1
    categories_url_format: "{slug}"
    categories_allowed:
      - Buzz
      - Events
      - Resources
  autorefs:
    resolve_closest: true  # autorefs warns of the Usage headings begin duplicates without this - we will have to assign unique ids to all of them otherwise
  macros:
    module_name: macros
    include_yaml:
        - team: en/news/.authors.yml
  meta: {}
  rss:
    feed_title: "BeeWare: The Buzz"
    feed_description: News and events for the BeeWare project.
    match_path: "news/posts/.*"
    use_git: false  # Forces it to read the dates from the frontmatter.
    date_from_meta:
      as_creation: "date"
      datetime_format: "%Y-%m-%d"
    categories:
      - categories
    feeds_filenames:
      rss_created: news/buzz/atom.xml
#    image: images/brutus.png  # Update to a Brutus URL
    abstract_chars_count: -1
  redirects:
    redirect_maps:
      # shortlinks
      "bee/briefcase-bootstraps.md": "https://briefcase.beeware.org/en/latest/reference/commands/new.html#third-party-bootstraps"
      "bee/chat.md": "https://discord.gg/AjYYm8cyQM"
      "bee/coc.md": "community/code-of-conduct.md"
      "bee/join.md": "membership/index.md"
      "bee/podium.md": "https://github.com/beeware/podium"
      "bee/signup.md": "about/contact.md"
      "bee/sprint.md": "contributing/sprint-guide.md"
      "bee/sprints.md": "contributing/sprint-guide.md"
      # Historical links of significance
      "community/behavior/code-of-conduct.md": "community/code-of-conduct.md"
